# Generated by Django 4.0.3 on 2022-11-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_tag_post_likes_post_tags'),
        ('authApp', '0002_remove_usermodel_password2_alter_usermodel_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_favos', to='blogApp.post'),
        ),
    ]
